#!/bin/bash
echo "Initializing lxd..."
cat node_config | lxd init --preseed

echo "Downloading base image..."
wget https://storage.surfly.com/surfly-public/d8_base.7b9c9f.tar.gz -O /tmp/image.tar.gz

echo "Importing image to lxd..."
lxc image import /tmp/image.tar.gz --alias d8_base

echo "Creating surfly container..."
lxc launch d8_base surflyc

echo "Configuring container..."
# Required by runit
lxc config set surflyc security.privileged true
lxc config device add surflyc myport80 proxy listen=tcp:0.0.0.0:80 connect=tcp:127.0.0.1:80
lxc config device add surflyc myport443 proxy listen=tcp:0.0.0.0:443 connect=tcp:127.0.0.1:4433 proxy_protocol=true

echo "Restarting container..."
sleep 3 && lxc restart surflyc
